from app import db # we already defined db instance inside app/__init__.py file
import datetime
from app.auth.models import User
from app.admin_panel.models import Project, Task


class Session(db.Model):
    __tablename__ = 'Session'
    id = db.Column(db.Integer, primary_key = True)

    #relationship
    t_id = db.Column(db.Integer, db.ForeignKey('Task.id'))

    s_start_time = db.Column(db.DateTime, default = datetime.datetime.utcnow())
    s_end_time = db.Column(db.DateTime, nullable = True)
    status = db.Column(db.String(100))

    def __init__(self, t_id, s_start_time, status):
                self.t_id = t_id
                self.s_start_time = s_start_time
                self.status = status

################## Worker class ##############################
class Worker(db.Model):
    __tablename__ = 'Worker'

    id = db.Column(db.Integer, primary_key = True)
    AMT_worker_id = db.Column(db.String(100)) #auto-generated by AMT
    # assign_id = db.Column(db.String(100))
    # arrival_time = db.Column(db.DateTime, default = datetime.datetime.now())
    def __init__(self, AMT_worker_id):
                self.AMT_worker_id = AMT_worker_id
######################## END ###################################

################## Assignments class ##############################
class Assignments(db.Model):
    __tablename__ = 'Assignments'

    id = db.Column(db.Integer, primary_key = True)
    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    hit_id = db.Column(db.String(100))
    assign_id = db.Column(db.String(100))
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    status_id = db.Column(db.Integer, db.ForeignKey('WorkerStatus.id'), nullable = True)
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, w_id, hit_id, assign_id, s_id, time_stamp):
                self.w_id = w_id
                self.hit_id = hit_id
                self.assign_id = assign_id
                self.s_id = s_id
                self.time_stamp = time_stamp
######################## END ###################################


################## LiveStatus class ##############################
class LiveStatus(db.Model):
    __tablename__ = 'LiveStatus'

    id = db.Column(db.Integer, primary_key = True)
    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    status_id = db.Column(db.Integer, db.ForeignKey('WorkerStatus.id'))
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, w_id, s_id, status_id, time_stamp):
                self.w_id = w_id
                self.s_id = s_id
                self.status_id = status_id
                self.time_stamp = time_stamp
######################## END ###################################

################## DetailedStatus class ##############################
#This table will not update rows, rather it will add new row for each update
class DetailedStatus(db.Model):
    __tablename__ = 'DetailedStatus'

    id = db.Column(db.Integer, primary_key = True)
    ls_id = db.Column(db.Integer, db.ForeignKey('LiveStatus.id'))
    status = db.Column(db.Integer, db.ForeignKey('WorkerStatus.id'))
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, ls_id, status, time_stamp):
                self.ls_id = ls_id
                self.status = status
                self.time_stamp = time_stamp
######################## END ###################################

################## WorkerStatus class ##############################
class WorkerStatus(db.Model):
    __tablename__ = 'WorkerStatus'

    id = db.Column(db.Integer, primary_key = True)
    status = db.Column(db.String(100))

    def __init__(self, status):
                self.status = status
######################## END ###################################

################## Message class ##############################
class Message(db.Model):
    __tablename__ = 'Message'

    id = db.Column(db.Integer, primary_key = True)
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    text = db.Column(db.String(500), nullable = False)
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, s_id, text, time_stamp):
                self.s_id = s_id
                self.text = text
                self.time_stamp = time_stamp

######################## END ###################################

################## Message class ##############################
class Robot(db.Model):
    __tablename__ = 'Robot'

    id = db.Column(db.Integer, primary_key = True)
    Name = db.Column(db.String(100), nullable = False)
    model = db.Column(db.String(100), nullable = True)

    def __init__(self, Name):
                self.Name = Name

    @classmethod
    def create_robot(cls, Name):
        robot = cls(Name=Name)
        db.session.add(robot)
        db.session.commit()
        return robot

######################## END ###################################

################## SpokenByUser class ##############################

#This class will store messages that will be received from participant(s) (Transcribed through Speech-to-Text services)

class SpokenByUser(db.Model):
    __tablename__ = 'SpokenByUser'

    id = db.Column(db.Integer, primary_key = True)

    r_id = db.Column(db.Integer, db.ForeignKey('Robot.id'))
    m_id = db.Column(db.Integer, db.ForeignKey('Message.id'))
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, r_id, m_id, time_stamp):
                self.r_id = r_id
                self.m_id = m_id
                self.time_stamp = time_stamp

######################## END ###################################

#This class will store messages that will be received from crowd-workers (Either typed or Transcribed through Speech-to-Text services)

class SpokenByRobot(db.Model):
    __tablename__ = 'SpokenByRobot'

    id = db.Column(db.Integer, primary_key = True)

    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    m_id = db.Column(db.Integer, db.ForeignKey('Message.id'))
    is_selected = db.Column(db.String(100), nullable = False)
    type = db.Column(db.String(100))
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, w_id, m_id, is_selected, time_stamp, type):
                self.w_id = w_id
                self.m_id = m_id
                self.is_selected = is_selected
                self.time_stamp = time_stamp
                self.type = type

######################## END ###################################

################## Reward class ##############################
class RewardWaiting(db.Model):
    __tablename__ = 'RewardWaiting'

    id = db.Column(db.Integer, primary_key = True)
    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    reward = db.Column(db.Float)
    waited_time = db.Column(db.String(100))
    # feedback = db.Column(db.String(100), default = "None")

    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, w_id, s_id, reward, waited_time):
                    self.w_id = w_id
                    self.s_id = s_id
                    self.reward = reward
                    self.waited_time = waited_time

################## Reward class ##############################
#the reason to keep both tables seperate was: in future there can be significant difference in both stages
class RewardActive(db.Model):
    __tablename__ = 'RewardActive'

    id = db.Column(db.Integer, primary_key = True)
    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    no_of_msgs = db.Column(db.Integer, default=0)
    selected_msgs = db.Column(db.Integer, default=0)
    work_based_bonus = db.Column(db.Float, default=0.0)
    waited_time = db.Column(db.String(100), default="00:00:00")
    time_based_bonus = db.Column(db.Float, default=0.0)
    # feedback = db.Column(db.String(100), default = "None")
    time_stamp = db.Column(db.DateTime, default = datetime.datetime.utcnow())

    def __init__(self, w_id, s_id, no_of_msgs):
                    self.w_id = w_id
                    self.s_id = s_id
                    self.no_of_msgs = no_of_msgs

class SESSION_SQLALCHEMY(db.Model):
    __tablename__ = 'SESSION_SQLALCHEMY'

    id = db.Column(db.Integer, primary_key = True)
    Name = db.Column(db.String(100))

class Tutorial(db.Model):
    __tablename__ = 'Tutorial'
    id = db.Column(db.Integer, primary_key = True)
    w_id = db.Column(db.Integer, db.ForeignKey('Worker.id'))
    s_id = db.Column(db.Integer, db.ForeignKey('Session.id'))
    t_id = db.Column(db.Integer, db.ForeignKey('Task.id'))
    status = db.Column(db.Integer)
    join = db.Column(db.DateTime, default = datetime.datetime.utcnow())
    Leave = db.Column(db.DateTime, nullable = True)

    def __init__(self, w_id, s_id, t_id, status):
                    self.w_id = w_id
                    self.s_id = s_id
                    self.t_id = t_id
                    self.status = status
